### PR TITLE
quicklaunch: Add "Desktop Action" support

### PR DESCRIPTION
**Pull request by palinek**
This is ~~a dirty~~ implementation of lxde/lxqt#1319 and needs the lxde/libqtxdg#142

@luis-pereira @tsujan @PCMan 
~~Should we somehow incorporate something like `XdgDesktopAction` into the libqtxdg?~~

closes lxde/lxqt#1319

### CODE REVIEW

**Comment by palinek** [comment]
> Should we somehow incorporate something like XdgDesktopAction into the libqtxdg?

Already done so... and IMO it's straightforward enough.

Also updated the "dirty" code here... now I think it can be merged.

**Comment by tsujan** [comment]
GTM.

There's a small issue that isn't related to this PR (which can be merged as it is) but should be fixed sooner or later, especially now that the context menu can contain more interesting items: all  context menus are aligned to the the first icon. The following screenshot shows the context menu of Gimp but its position isn't suitable:

position

Actually, if context menus were really bound to their buttons (icons), also Kvantum could calculate the bottom shadow of the menu and position it lower. I guess binding menus to buttons might require fundamental changes.

Sorry for reporting a bug in a PR ;)

**Comment by agaida** [comment]
@tsujan - and please don't forget to file a separate bug :D

**Comment by tsujan** [comment]
@agaida Sure! I'll look into it later.

**Pull request merged**
