### PR TITLE
plugin-clock: content down-scaling & proper size adjustments after config changes

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/lxqt#660

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@Vladimir-csp, please teste it.

**Comment by Vladimir-csp** [comment]
It looks nice, but it has a bug:
Open clock configuration, change date format to something that does not fit. It scales accordingly.
Then change first day of the week or flap rotation on and off again, scaling disappears.

**Comment by palinek** [comment]
@Vladimir-csp yes there are minor problems with the first repaint after config change... but I was completely pissed by fiddling with that arround and gave up..
(after time change, the style is corrected... so clicking on "show seconds" on/off is a workaround to show correct formatting instantly)

**Comment by Vladimir-csp** [comment]
Aside from that it works as it should. Thanks!

**Comment by paulolieuthier** [comment]
Merge it.

**Comment by palinek** [comment]
landed in @a4a16c2

**Pull request closed without merging**
