### PR TITLE
plugin-mount: switch from liblxqt-mount to KF5Solid

### PR DESCRIPTION
**Pull request by palinek**
from lxde/lxqt#95 got here... as @jleclanche suggested move to KF5Solid

### CODE REVIEW

**Comment by jleclanche** [comment]
1. Can you rebase on current master? there have been syntax changes
2. Can you fix your git name to include your real name? This is required if you want credit.

**Comment by palinek** [comment]
1. currently merging rebase conflicts
2. i'm not sure if i do want such publicity

**Comment by jleclanche** [comment]
Ok, anonymity is fine in the commits.

**Comment by palinek** [comment]
@jleclanche merged....
And a note about compiling (that we were discussing with Jerome): I needed to put additional include dir into CMakeLists.txt on my system (seems that KF5SolidConfig.cmake is not OK ..):
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -56,6 +56,7 @@ include_directories(
     ${LXQT_INCLUDE_DIRS}
     ${QTXDG_INCLUDE_DIRS}
     ${Qt5X11Extras_INCLUDE_DIRS}
+    /usr/include/KF5/Solid
 )
```

**Comment by jleclanche** [comment]
I didn't have to do that.

**Comment by paulolieuthier** [comment]
@palinek that additional include dir should go in the plugins' CMakeLists.txt. If one wants not to build this plugin and doesn't want Solid, he doesn't need this include dir.

**Comment by jleclanche** [comment]
For the record, I didn't mean for you to squash the failure notification commit, that is separate. But no matter.

**Comment by jleclanche** [comment]
Pointed out some style issues for now. The code looks good overall. Need to test stuff.

If this is good enough I would like to land it early. We can do further improvements to the mount plugin as followups.

**Comment by jleclanche** [comment]
I'm glad to see MountManager gone, btw.

**Comment by palinek** [comment]
@jleclanche, @paulolieuthier commited...

**Comment by jleclanche** [comment]
lgtm once squashed.

**Comment by palinek** [comment]
@jleclanche squashed...

**Comment by jleclanche** [comment]
@paulolieuthier @luis-pereira @PCMan can one of you give your gtm as well please and this will land.

**Comment by paulolieuthier** [comment]
I'm testing it right now.

**Comment by paulolieuthier** [comment]
@palinek @jleclanche my internet connection today is very crappy. Just wanted to say that by grepping lxqt components, the only component that uses liblxqt-mount is lxqt-panel, on the mount plugin.

**Comment by luis-pereira** [comment]
Started to test it.

**Comment by jleclanche** [comment]
@luis-pereira merge at your discretion, then. this already got 2 GTMs.

**Comment by luis-pereira** [comment]
@palinek Thanks.
There are some styling issues, but they are minor
@jleclanche the liblxqt-mount isn't needed anymore. Can you reflect it on the git super repo and on the build scripts ? I have to run and won't be available until tomorrow.

**Pull request merged**
