### PR TITLE
plugin-spacer: support for stylable spaces

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by palinek** [comment]
@intialonso here is the agreed support for styling

**Comment by intialonso** [comment]
Great! I will test this night (or tomorrow if beers happen)!

**Comment by palinek** [comment]
@intialonso did you test this?

**Comment by intialonso** [comment]
Im sorry, I havent had time yet. Im having a lot of work this days. I will
find some time before the weekend.

**Comment by intialonso** [comment]
@palinek Im sorry but Im a llittle lost in how to test this (Im a designer, and Im not too good managing github), I see that this is not merged so in my install this changes are not available, Do I have to compile this? Can you point me how to do it?

**Comment by palinek** [comment]
@intialonso I don't know how are you testing changes on master...but you are probably compliing from sources cloned from github. If so you just need to clone lxqt-panel from my fork (particular branch), something like this:
```
~/work/oss/lxqt$ git clone https://github.com/palinek/lxqt-panel.git
Cloning into 'lxqt-panel'...
remote: Counting objects: 11907, done.
remote: Total 11907 (delta 0), reused 0 (delta 0), pack-reused 11907
Receiving objects: 100% (11907/11907), 3.85 MiB | 703.00 KiB/s, done.
Resolving deltas: 100% (7538/7538), done.
Checking connectivity... done.
~/work/oss/lxqt$ cd lxqt-panel
~/work/oss/lxqt/lxqt-panel$ git checkout plug_spacer
Branch plug_spacer set up to track remote branch plug_spacer from origin.
Switched to a new branch 'plug_spacer'
~/work/oss/lxqt/lxqt-panel$ git branch -v
  master      6b39aaa plugin-mount: switch from liblxqt-mount to KF5Solid
* plug_spacer 6332cba plugin-spacer: corrected spelling
```
...and compile/install as you used to. Don't know if this helps..

**Comment by paulolieuthier** [comment]
It's all looking very good, except for keeping the separator types in a list of strings. IMO, there should be a `enum` for it, and [helper functions](https://github.com/lxde/lxqt-panel/blob/master/panel/lxqtpanel.cpp#L80) for getting the strings.

**Comment by palinek** [comment]
@paulolieuthier hm.. I don't see a reason to have it as enum:
1. there is no logic connected to the type. It is only for style applying
2. the type can be any string that the user configures (in configuration, the combo is editable) => the end user can have his/her own special type for styling

**Comment by paulolieuthier** [comment]
I see now. I've tested and it's working. But I'd rather giving the user a few uneditable options to choose, I don't get the point of making it editable. Let's wait for the opinion of others.

**Comment by intialonso** [comment]
Ok, I have it installed, it is working fine. Im with Paulo, the options should be fixed, making it editable could lead to mistakes from the user and broken settings.

**Comment by intialonso** [comment]
@palinek I need to remove and add the plugin again to load the new styles. It doesnt change on the fly.

**Comment by palinek** [comment]
As you wish...
1. @paulolieuthier IMO the enum is not needed (as I've said there is no logic connected to that and the enum <-> string conversion will be needles and will only reduce the performance)
2. @intialonso are the predefined names suitable for all use cases? If we name it only as type1, type2, type3.. theme creator will have free hands to style it in any way he/she wants and the predefined names will not confuse user
3. @intialonso i think that for designer it will be good to know if the spacer is on horizontal or vetical panel (e.g. for styling only the top/down vs. left/right). Should I put ther also this property (let's call it ```orientation```)?

**Comment by palinek** [comment]
> I need to remove and add the plugin again to load the new styles. It doesnt change on the fly.
@intialonso i think, i've read an issue about that, but can't find it right now. Can you, guys @paulolieuthier, @jleclanche, remember that?

**Comment by intialonso** [comment]
@palinek the orientation could be resolved as in the other plugins ? (with an Autorotate option, see the Clock plugin or the Task one) That way we dont need more styles.

The predefined names should be self explanatory, I think that if some user want to do and advanced customizitation, the names should be no impediment, and keeping the names clear and descriptive will be helpful for novice users.

**Comment by paulolieuthier** [comment]
@palinek this is what I mean:

xfce's way

**Comment by intialonso** [comment]
After some test I decided to set this using the background-image property like this: 

```
#Spacer[type="lined"] {
    background-image: url(spacer-line.svg);
    background-position: center center;
    background-repeat: repeat-y;
}

#Spacer[type="dotted"] {
    background-image: url(spacer-dots.svg);
    background-position: center center;
    background-repeat: repeat-y;
}
```

This way the line will be always in the center of the pluging regardless of the width, and it will not scale horizontally to avoid a color box if the pluging width is too high.

Screenshot: The firs one is the widget with border enabled (we get a ugly box). The other two are the background-image style.

rect4195

**Comment by paulolieuthier** [comment]
@intialonso this is very good. What about when the panel is vertical?

**Comment by intialonso** [comment]
@paulolieuthier I asked before if the orientation could be resolved as in the other plugins (with an Autorotate option, see the Clock plugin or the Task one) That way we dont need more styles.

If no, the we can use the Palinek proposal and use a "position" property (as the panel LxQtPanel[position="Top"]).

**Comment by paulolieuthier** [comment]
Oh, yes. You're right.

**Comment by palinek** [comment]
Removed option to edit the type manualy in configuration and added property orientation.
@intialonso now the style could be as following:
```css
#Spacer {
    background-position: center center;
}

#Spacer[type="lined"] {
    background-image: url(spacer-line.svg);
}

#Spacer[type="dotted"] {
    background-image: url(spacer-dots.svg);
 }

#Spacer[orientation="horizontal"] {
    background-repeat: repeat-y;
}

#Spacer[orientation="vertical"] {
    background-repeat: repeat-x;
}
```
...also was looking/trying the LxQt::RotatedWidget and using it for "no-content" widget is IMHO an overkill and performance drawback

**Comment by paulolieuthier** [comment]
@palinek great! Please rebase and squash the commits.

**Comment by palinek** [comment]
@paulolieuthier should I also land this?

**Comment by palinek** [comment]
> I need to remove and add the plugin again to load the new styles. It doesnt change on the fly.

@intialonso tested this and for me styles are update immediately (as soon as the the ```lxqt-panel.qss``` is updated)

**Comment by paulolieuthier** [comment]
> @paulolieuthier should I also land this?

@palinek sure. And @intialonso please commit the styles.

**Comment by intialonso** [comment]
Im at the office now, as soon as I get some free time I will get all the themes updated.

**Comment by intialonso** [comment]
@palinek the styles are not working with the [orientation] property. For example, try changing the background color; it does no have any effect, same for the background-repeat settings.

Can you please confirm if it is working for you?

**Comment by palinek** [comment]
@intialonso for me it's working. With following example configuration:
```css
#Spacer[type="invisible"] {
    background-color: blue;
}

#Spacer[orientation="horizontal"] {
    border-bottom: 10px solid black;
    border-top: 10px solid black;
}

#Spacer[orientation="vertical"] {
    border-bottom: 10px solid white;
    border-top: 10px solid white;
}
```
... i am getting:
- horizontal panel:
screenshot
- vertical panel:
screenshot

**Comment by intialonso** [comment]
@palinek must be something in my system, even with that last example it does not work (I get no borders). Im running Manjaro with LXQT from AUR. I will try on my Ubuntu install.

**Comment by palinek** [comment]
@intialonso did you fetched last change for this? 65f14fd6e6701b925dc9ceed23da28f004a80c28

**Comment by intialonso** [comment]
Im compiling from master.

**Comment by palinek** [comment]
Strange... let's wait for someone else if it's working for him/her.

**Comment by paulolieuthier** [comment]
@intialonso make sure you are using the latest version of lxqt-config, liblxqt and lxqt-qtplugin as well.

**Comment by intialonso** [comment]
@paulolieuthier I have updated everything again from aur and no, is not working. Im clueless.

**Comment by intialonso** [comment]
Finally, I did a new install in Antergos and it worked. I will start the theming.

**Pull request merged**
