### PR TITLE
Russian translations for the kbindicator plugin

### PR DESCRIPTION
**Pull request by f2404**

### CODE REVIEW

**Comment by palinek** [comment]
If there is no difference between the universal (_ru) and the country specific (_ru_RU) we are trying to avoid the duplicity and maintaining only the universal one.

@f2404 If there is difference, please, provide only the _ru* files.

**Comment by f2404** [comment]
@palinek There's no difference between the translations. I will remove the _ru_RU files.
However, I can see that most of other modules contain both _ru and _ru_RU. Are you planning to clean them up?

**Comment by palinek** [comment]
> However, I can see that most of other modules contain both _ru and _ru_RU. Are you planning to clean them up?

Actualy, yes. We would like, but we are lacking manpower...

**Comment by f2404** [comment]
Ok, I will use my another PR for that.

**Comment by paulolieuthier** [comment]
Merged. Thanks.

**Pull request closed without merging**
