### PR TITLE
Include sources which export used functions

### PR DESCRIPTION
**Pull request by jubalh**
It seems that this is needed on my system to compile without any
errors/warnings.
Patch is provided by hrvoje.senjan@gmail.com.

Please review this.

### CODE REVIEW

**Comment by palinek** [comment]
What was the orginal problem leading to this?

**Comment by jubalh** [comment]
It didnt compile becaues it couldnt find some functions

**Comment by palinek** [comment]
> It didnt compile becaues it couldnt find some functions

Could you be more specific about the environement, err output etc...?

**Comment by jubalh** [comment]
Of course:
```
[   56s] cd /home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build/plugin-showdesktop && /usr/lib64/qt5/bin/lrelease /home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/plugin-showdesktop/translations/showdesktop_lt.ts -qm /home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build/plugin-showdesktop/showdesktop_lt.qm
[   56s] Updating '/home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build/plugin-networkmonitor/networkmonitor_fr.qm'...
[   56s]     Generated 17 translation(s) (17 finished and 0 unfinished)
[   56s] [ 67%] Building CXX object plugin-sysstat/CMakeFiles/sysstat.dir/lxqtsysstat.cpp.o
[   56s] cd /home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build/plugin-sysstat && /var/lib/build/ccache/bin/c++  -DLXQT_DATA_DIR=\"/usr/share\" -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\" -DLXQT_VERSION=\"0.10.0\" -DPLUGIN_DIR=\"/usr/lib64/lxqt-panel\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -DWITH_CLOCK_PLUGIN -DWITH_DESKTOPSWITCH_PLUGIN -DWITH_MAINMENU_PLUGIN -DWITH_QUICKLAUNCH_PLUGIN -DWITH_SHOWDESKTOP_PLUGIN -Dsysstat_EXPORTS -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -std=c++11 -fPIC -I/home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build/plugin-sysstat -I/home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/plugin-sysstat -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/lxqt -isystem /usr/include/lxqt/LXQt -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5 -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5xdg -isystem /usr/include/qt5xdg/1.3.0 -isystem /usr/include/qt5/QtXml -isystem /usr/include/sysstat-qt5    -Wall -fPIC -o CMakeFiles/sysstat.dir/lxqtsysstat.cpp.o -c /home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/plugin-sysstat/lxqtsysstat.cpp
[   56s] CMakeFiles/mount.dir/configuration.cpp.o: In function `Configuration::devAddedChanged(int)':
[   56s] configuration.cpp:(.text+0x5f): undefined reference to `LXQtPanelPluginConfigDialog::settings() const'
[   56s] CMakeFiles/mount.dir/configuration.cpp.o: In function `Configuration::~Configuration()':
[   56s] configuration.cpp:(.text+0x169): undefined reference to `LXQtPanelPluginConfigDialog::~LXQtPanelPluginConfigDialog()'
[   56s] CMakeFiles/mount.dir/configuration.cpp.o: In function `Configuration::loadSettings()':
[   56s] configuration.cpp:(.text+0x1d2): undefined reference to `LXQtPanelPluginConfigDialog::settings() const'
[   56s] configuration.cpp:(.text+0x21c): undefined reference to `LXQtPanelPluginConfigDialog::setComboboxIndexByData(QComboBox*, QVariant const&, int) const'
[   56s] CMakeFiles/mount.dir/configuration.cpp.o: In function `Configuration::Configuration(QSettings&, QWidget*)':
[   56s] configuration.cpp:(.text+0x262): undefined reference to `LXQtPanelPluginConfigDialog::LXQtPanelPluginConfigDialog(QSettings&, QWidget*)'
[   56s] CMakeFiles/mount.dir/configuration.cpp.o: In function `Configuration::~Configuration()':
[   56s] configuration.cpp:(.text+0x12a): undefined reference to `LXQtPanelPluginConfigDialog::~LXQtPanelPluginConfigDialog()'
[   56s] CMakeFiles/mount.dir/mount_automoc.cpp.o: In function `Configuration::qt_metacall(QMetaObject::Call, int, void**)':
[   56s] mount_automoc.cpp:(.text+0xb61): undefined reference to `LXQtPanelPluginConfigDialog::qt_metacall(QMetaObject::Call, int, void**)'
[   56s] CMakeFiles/mount.dir/mount_automoc.cpp.o: In function `Configuration::qt_metacast(char const*)':
[   56s] mount_automoc.cpp:(.text+0xb3d): undefined reference to `LXQtPanelPluginConfigDialog::qt_metacast(char const*)'
[   56s] CMakeFiles/mount.dir/mount_automoc.cpp.o:(.data.rel.ro._ZTI13Configuration[_ZTI13Configuration]+0x10): undefined reference to `typeinfo for LXQtPanelPluginConfigDialog'
[   56s] CMakeFiles/mount.dir/mount_automoc.cpp.o:(.data.rel.ro._ZTV13Configuration[_ZTV13Configuration]+0x1e0): undefined reference to `LXQtPanelPluginConfigDialog::dialogButtonsAction(QAbstractButton*)'
[   56s] CMakeFiles/mount.dir/mount_automoc.cpp.o:(.data.rel.ro+0x100): undefined reference to `LXQtPanelPluginConfigDialog::staticMetaObject'
[   56s] collect2: error: ld returned 1 exit status
[   56s] plugin-mount/CMakeFiles/mount.dir/build.make:532: recipe for target 'plugin-mount/libmount.so' failed
[   56s] make[2]: *** [plugin-mount/libmount.so] Error 1
[   56s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/lxqt-panel-0.10.0/build'
[   56s] CMakeFiles/Makefile2:705: recipe for target 'plugin-mount/CMakeFiles/mount.dir/all' failed
[   56s] make[1]: *** [plugin-mount/CMakeFiles/mount.dir/all] Error 2
```

**Comment by palinek** [comment]
This is not enough :(
Seems that the building process is paralel (make -jX) ... so the message about building plugin-sysstat is not connected to the failure in plugin-mount

**Comment by luis-pereira** [comment]
How does this patch fixes it ?

**Comment by paulolieuthier** [comment]
@jubalh I don't think this is really needed. Try erasing your build folder first and trying building again.

**Comment by paulolieuthier** [comment]
I'm closing this, reopen if the problem persists.

**Pull request closed without merging**
