### PR TITLE
Cleaned pull request for german translations for Tray+volume+worldclock

### PR DESCRIPTION
**Pull request by ThomasVie**
Implemented comment by Philipp.

### CODE REVIEW

**Comment by philippwiesemann** [comment]
Thank you for fixing the translation. :)

**Comment by paulolieuthier** [comment]
@ThomasVie your branch is very different from our master. You have to sync it before creating the pull request.

**Comment by paulolieuthier** [comment]
screen

**Comment by ThomasVie** [comment]
> your branch is very different from our master. You have to sync it before creating the pull request.

Please don't compare my master branch wuth upstream master's.
Compare the branch of the pull request instead.
Is it better than?
Thomas

**Comment by paulolieuthier** [comment]
Merge:
1627be9620793c2083cdad54aeae3298d379e19c
4b9a01b064aa01c146f44182c5eb5c05a83a8115
95e7abd1559c440531123aecae5fbd0ba9a3c528

**Pull request closed without merging**
