### PR TITLE
taskbar: Add visual effect to button move

### PR DESCRIPTION
**Pull request by palinek**
(this needs the lxde/liblxqt#67)

### CODE REVIEW

**Comment by paulolieuthier** [comment]
The visual feedback is very nice. But now I think we can disable the floating pixmap. Don't you think?

**Comment by palinek** [comment]
Hm... I wouldn't remove it.... but my 2 cents is to set it just to the icon:
```
--- a/plugin-taskbar/lxqttaskbutton.cpp
+++ b/plugin-taskbar/lxqttaskbutton.cpp
@@ -266,10 +266,8 @@ void LXQtTaskButton::mouseMoveEvent(QMouseEvent* event)
     QDrag *drag = new QDrag(this);
     drag->setMimeData(mimeData());
 
-    //fixme when vertical panel, pixmap is empty
-    QPixmap pixmap = grab();
-    drag->setPixmap(pixmap);
-    drag->setHotSpot(QPoint(mapTo(this, event->pos())));
+    QIcon ico = icon();
+    drag->setPixmap(ico.pixmap(ico.actualSize({32, 32})));
 
     sDraggging = true;
     drag->exec();
```

**Comment by paulolieuthier** [comment]
You're right.

**Comment by paulolieuthier** [comment]
GTM.

**Pull request merged**
