### PR TITLE
panel: auto-hide feature

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/lxqt#134

I had a look at @rootzrich work (https://github.com/lxde/lxqt-panel/compare/master...rootzrich:autohide_tb_qt5). Maybe I'm missing something but it seems to me a bad idea to pull all the XCB dependencies...

I tried to achieve hiding in a simple way (hiding the bacground widget) and it seems to work. It's still an pre-alpha and some plugins have problems with hiding.

I will appreciate all comments or event help...

### CODE REVIEW

**Comment by jleclanche** [comment]
Looks fantastically straightforward. I can't do anythin in-depth right now so ill leave it off to others to review.

**Comment by paulolieuthier** [comment]
The problem with the other implementation was that the panel was hidding when the user right-clicked the panel or a plugin, and it shouldn't.

**Comment by palinek** [comment]
@paulolieuthier this one doesn't have such problem

**Comment by paulolieuthier** [comment]
Awesome. I'll test it.

**Comment by palinek** [comment]
Now it seems to be usable.
Just when some popup is open and mouse leaves panenl over it... panel doesn't receive LeaveEvent and stays open. For this I have no clue how to fix it right now.

**Comment by luis-pereira** [comment]
Good job :) GTM Should be merge to master to get more testing.

**Comment by paulolieuthier** [comment]
Agreed.

**Comment by jleclanche** [comment]
Ship it then.

**Comment by palinek** [comment]
Oh... that was quick. Seems like you are realy waiting for this feature.

**Comment by jleclanche** [comment]
@palinek if the code overall looks good and gets approved by 3 devs, might as well have it tested in master rather than in a branch none of us run day to day ;)

**Comment by inderpreetsingh** [comment]
How to enable this?

**Comment by palinek** [comment]
@inderpreetsingh  Right click on panel -> Configure panel -> (tab Panel) -> (section Alignment & position) -> Auto-hide

**Pull request merged**
