### PR TITLE
avoid inifinite recusion when no icon avaible.

### PR DESCRIPTION
**Pull request by comicfans**
this fix https://github.com/lxde/lxqt/issues/1431

### CODE REVIEW

**Comment by tsujan** [comment]
Looks GTM.

**Comment by tsujan** [comment]
@comicfans Could you please add a short but informative comment to those lines, with the style used in the code?

**Comment by comicfans** [comment]
Hi @tsujan , I've added comment as you suggested.

**Comment by tsujan** [comment]
That's good -- except for its English :D

**Comment by comicfans** [comment]
Not my native language,  maybe you need to improve my comment ...

**Comment by tsujan** [comment]
> Not my native language...

Neither mine; was just joking. Those arrows (->) explain everything concisely.

**Comment by comicfans** [comment]
never mind , actually I'd like someone improve my comment that also improve my English :)

**Comment by tsujan** [comment]
It's not so important. Just, instead of
```
// some theme is lack of "unknown" icon, null check prevent infinite
recursion....
```
it could be said (with your words):
```
Some themes may lack the "unknown" icon; checking null prevents infinite
recursion....
```

**Comment by comicfans** [comment]
well , thank you :)

**Comment by palinek** [comment]
@comicfans please, change the comment wording as suggested.... then GTM

**Comment by comicfans** [comment]
hi @palinek ,already re-pushed

**Comment by palinek** [comment]
Great... merging. Thanks.

**Pull request merged**
