### PR TITLE
Kbd layout plugin (2 iteration)

### PR DESCRIPTION
**Pull request by zjes**
Just simple plugin to show current language/caps lock status in panel, can remember layout per windows, applications or global.

### CODE REVIEW

**Comment by zjes** [comment]
Hi, sorry for lo-o-o-ong delay. :( 
Kbd layout was merged  to kbdindicator plugin. I hope it will be useful.

**Comment by zjes** [comment]
Anybody here? :)

**Comment by jleclanche** [comment]
@zjes Thanks for the update. Are you willing to work with me to make this a third party plugin? Note that this doesn't mean it won't get merged here, but I'd like to take the occasion to work on our third party plugin support system.

**Comment by zjes** [comment]
Yes, but one question, in this third party plugin will whole kbdindicator plugin or just layout's part? :)

**Comment by jleclanche** [comment]
Up to you. Ideally I'd like to have just one keyboard plugin in LXQt with all the necessary functionality, but for now this is just a step forward.

**Comment by zjes** [comment]
Ok, 
might you describe your vision of the organization such third party plugins?

**Comment by jleclanche** [comment]
I'd like to see the user including a lxqt-panel cmake file and just have to set the plugin name etc, and it'll get installed to /usr/lib/lxqt-panel/ and the panel will be able to find it.

**Comment by zjes** [comment]
This is good, 
but what about separated git, no main maintainers, not under lxqt roadmap, version's conflicts... ?
Ok, i'll try to make such plugin.

**Comment by jleclanche** [comment]
@zjes yes, that's the idea of third party plugins. :)

**Comment by paulolieuthier** [comment]
Closed. See the third party plugin: https://github.com/zjes/lxqt-kbdstatel.

**Comment by luis-pereira** [comment]
@jleclanche me too. We will get there :smile:

**Pull request closed without merging**
