### PR TITLE
Added dependency xkbcommon-x11 to kbindicator-plugin

### PR DESCRIPTION
**Pull request by agaida**
fixes lxde/lxqt/issues/1381

### CODE REVIEW

**Comment by yan12125** [comment]
There's already a line referencing xkbcommon-x11:
https://github.com/lxde/lxqt-panel/blob/dc91516015e3b7c762561ed6c5e4bafb652fd816/plugin-kbindicator/CMakeLists.txt#L32
I'm not sure why it doesn't work. If this is the correct version, maybe removing that part can prevent some confusion.

**Comment by agaida** [comment]
@yan12125 - good point. It should just work™ - but now we are on it - wouldn't it be wise to centralize the needed dependencies into the root CMakeLists.txt?

**Comment by yan12125** [comment]
+1 for placing all ```find_package``` calls in root CMakeLists.txt - that can be worked out after this is fixed.

**Comment by tsujan** [comment]
> There's already a line referencing xkbcommon-x11

Is this about a cmake bug or am I missing something?

**Comment by yan12125** [comment]
Looks like it's still our business :) https://github.com/lxde/lxqt-build-tools/blob/master/cmake/find-modules/FindXCB.cmake

**Comment by luis-pereira** [comment]
@agaida There's no `Findxkbcommon-x11.cmake` nor `xkbcommon-x11Config.cmake` nor `xkbcommon-x11-config.cmake`.
It just fails. Did you test it ?

**Comment by agaida** [comment]
@luis-pereira - i guess not hard enough - but the good thing is - there was a fruitful discussion about moving the finds to a central place (CMakeLists.txt) and your upcoming fix of the current behaviour - so i guess this PR can be closed right now as obsolete.

**Pull request closed without merging**
