### PR TITLE
Cleanup of CMakes, using GNUInstallDirs now

### PR DESCRIPTION
**Pull request by paulolieuthier**
Fixes lxde/lxqt#428.

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm

**Comment by jleclanche** [comment]
Merging it because we need this in arch.

**Comment by jleclanche** [comment]
@paulolieuthier can you take care of qtermwidget/qterminal as well? it also uses LIB_SUFFIX.

**Comment by paulolieuthier** [comment]
Will do.

**Comment by luis-pereira** [comment]
Ok. nice.

**Pull request merged**
