### PR TITLE
Rename LxQt to LXQt in .ts files

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by jubalh** [comment]
Can the "Name" tag be changed without code changes?

**Comment by jubalh** [comment]
This PR can only be merged after the class names got changed in the code

**Comment by agaida** [comment]
@jubalh - the time is now

**Comment by paulolieuthier** [comment]
@jubalh please, rebase.

**Comment by jubalh** [comment]
@paulolieuthier unfortunately i will be away the next 5 days. i can do it after that. if not: please go ahead and rebase! :)

**Comment by pmattern** [comment]
In the meantime the vast majority of the files covered by this PR has already been corrected in 7fa6c38 so I quickly fixed the remaining ones in 099f32d which seemed the easier approach.

**Comment by paulolieuthier** [comment]
Nice.

**Pull request closed without merging**
