### PR TITLE
Shows windows from current screen only option 

### PR DESCRIPTION
**Pull request by zjes**
Shows windows in taskbar for current screen only. It's mostly the same as desktop only, but additionaly filters windows by taskbar's screen (monitor)

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@zjes, thanks! Does this fix lxde/lxqt#169?

**Comment by zjes** [comment]
Yes, it looks similar. :)

**Comment by paulolieuthier** [comment]
@DaveDay @Vladimir-csp please take a look at this.

**Comment by jleclanche** [comment]
Taking the PR. Thank you for working on this, @zjes

**Comment by Vladimir-csp** [comment]
Cool! That is quite useful filter indeed for some setups. 
How will this affect config window? IMHO, radiobuttons should be changed to checkboxes:
- limit by current desktop
- limit by current screen

Ditching "show from all desktops, which is implied when nothing is checked.

If you are not considering tint2-like multidesktop mode, then this pull should fix #169. ...and I will open another issue in a desperate rescue attempt.

**Comment by zjes** [comment]
Radiobuttons can be replaced by checkboxes... doesn't matter. But IMHO little bit strange behavior to show tasks from all desktops, but only for current screen(but why not :)) and "undefined" non checked state (maybe needs to show help/notice that this state means "show windows from all desktops")

**Comment by Vladimir-csp** [comment]
When you have two filters that can be used indepently, checkboxes are The logical solution.
I used phrasing 'limit by' to imply filter nature of the options. If you think it`s not enough, add a note.

**Comment by zjes** [comment]
@jleclanche, @paulolieuthier change configuration to checkboxes or not?

**Comment by jleclanche** [comment]
Yes please

**Comment by paulolieuthier** [comment]
Someone with more then one screen can test this?

**Comment by palinek** [comment]
Tested... it's working. But the bad news is this implementation is on 'before grouping' tree.
Trying to merge it ito current master....

**Comment by palinek** [comment]
Landed in https://github.com/lxde/lxqt-panel/compare/f06970a76b32...9b46323700d2

**Pull request closed without merging**
