### PR TITLE
Add a threshold which a user has to pass when scrolling on the desktopswitch plugin

### PR DESCRIPTION
**Pull request by Grarap**
This makes scrolling less sensitive and more usable.

Fixes lxde/lxqt#479.

### CODE REVIEW

**Comment by Grarap** [comment]
(Just wanted to point out that something went seriously wrong here. Obviously neither me or anyone ever added those additional 6 commits which have nothing to do with this pull request and according to GitHub were added even before this pull request even existed.)

**Comment by paulolieuthier** [comment]
The PR is updated when you push changes to the branch the PR was made from. That's why it is recommended to give every PR its own branch. You can close this PR and create another one from another branch if you like, or keep this one and fix your master branch to have only your contributions on top of our master.

**Comment by Grarap** [comment]
I'm not sure if I understand your comment correctly, but this doesn't seem to me what's happened here.
I haven't touched my branch after that one commit. The additional commits are by other people, they are older and they are not part of my branch (master) which I created this PR from.

**Comment by paulolieuthier** [comment]
Yeah, it seems the original branch (ours) was changed somehow that made Github mess with the PR or something like that. Don't worry, after the release we take care of that.

**Comment by agaida** [comment]
@paulolieuthier @jleclanche @PCMan  - only a thought - i think we should deliver a panel without jumping menus, fallback icons and so on - would make sense imho. In that case we should clean up that mess right now, not after the release :)

**Comment by paulolieuthier** [comment]
@agaida those things will be in 0.9, don't worry.

**Comment by jleclanche** [comment]
Yes they are

**Comment by paulolieuthier** [comment]
Landed in lxde/lxqt-panel@1ec332f0e119b76f4dc6cb221f7f05a3fcd2227b. Thanks!

**Pull request closed without merging**
