### PR TITLE
Updated / added german translation for Sensors+showdesktop+spacer plugins

### PR DESCRIPTION
**Pull request by ThomasVie**
... but how to translate this (how to add the tr() here)?:
spacerconfiguration.cpp:31:
const QStringList SpacerConfiguration::msTypes = 
    (QStringList()
     << QStringLiteral("lined")
     << QStringLiteral("dotted")
     << QStringLiteral("invisible")

### CODE REVIEW

**Comment by palinek** [comment]
> ... but how to translate this 

@ThomasVie you're right... changed in @a04b477

**Comment by paulolieuthier** [comment]
@ThomasVie update your pull request now, please.

**Comment by paulolieuthier** [comment]
@ThomasVie thanks for your contributions! Now some reading to learn how to clean up a git repo's history (mainly rebase and squash): https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history.

**Comment by ThomasVie** [comment]
Thanks for the link. I'll try it next time. I already deleted my old branch.

**Pull request closed without merging**
