### PR TITLE
Autohide prevent

### PR DESCRIPTION
**Pull request by palinek**
closes lxde/lxqt#871

I don't know if I catched all the shown standalone windows.... please, check.

Update: closes lxde/lxqt#853

### CODE REVIEW

**Comment by palinek** [comment]
TODO: check if the periodic hide timer

**Comment by pmattern** [comment]
Couldn't see the problem discussed in lxde/lxqt#871 any longer with 0380ce1.

What I could see was the kind of problem discussed in lxde/lxqt#853 and friends.
E. g. after clicking on plugin-mount its GUI comes up (and unlike with earlier commits the panel stops auto-hiding as expected). If the UI gets closed by clicking outside the panel's UI the panel doesn't auto-hide at once, though, but only upon hovering.
But probably this is nothing new and was just sort of unmasked by 0380ce1 fixing lxde/lxqt#871.

Side note:
While testing this stuff I saw that there's some inconsistency as to how GUIs of panel plugins disappear.
Some like the ruler etc. from plugin-volume disappear as soon as the pointer is moved away, others like plugin-menu need a click outside their UI. Not sure what's the better approach or something needs to be changed at all, though. E. g. I find the behaviour of plugin-volume approprieate but as for the calendar that comes up on clicking plugin-[world-]clock I'd definitely vote for having it disappear upon a click outside only as viewing that calendar while e. g. hovering over some office document to compare dates is something rather common, IMO.
But just saying. Has nothing to do with the issue discussed here.

**Comment by palinek** [comment]
> E. g. after clicking on plugin-mount its GUI comes up (and unlike with earlier commits the panel stops auto-hiding as expected). If the UI gets closed by clicking outside the panel's UI the panel doesn't auto-hide at once, though, but only upon hovering.

Forgot to notify the panel for observing the window before each `show()` (was only for the first time being shown).... fixed and the commit *Prevent panel hiding...* updated. @pmattern can you confirm that it's working now?

**Comment by pmattern** [comment]
Latest b19afb1 is fixing both lxde/lxqt#871 and lxde/lxqt#853, IMO.

Notes on lxde/lxqt#853 (lxde/lxqt#629):
The panel does not auto-hide as long as a dialog like "Configure Panel" is open, even upon clicking somewhere else on the desktop. But the panel does auto-hide once the dialog is closed. IMO this is absolutely the right thing to do.
Never managed to reproduce that "first / following click" thing as described [here](https://github.com/lxde/lxqt/issues/853#issuecomment-150980502).
Also, I didn't bother trying to reproduce those somewhat mixed-up findings about particular applications like Gajim, LibreOffice and what not once as b19afb1 just seems to do the trick.

**Comment by palinek** [comment]
@pmattern thanks.

> You may want to let me know whether fiddling with some Qt 5.4 system as asked for here is still needed. Of course it could be done but would mean some effort I'd rather spare myself, tbh.

Actualy, with the new implementation we don't the "lost" `Leave` event that we were using for triggering the hide as described in lxde/lxqt#853 (as such updating the 1st post).

Merging...

**Comment by jeremywh7** [comment]
@palinek Looking good!  Almost all cases are resolved now; one that isn't is the quick launch; right-clicking it still makes the panel stick unhidden.  This relates to another issue; see #[2] below.  Also note that running Gajim does not specifically affect this as previously noted in [Issue 853](https://github.com/lxde/lxqt/issues/853#issuecomment-154055247).
>The panel does not auto-hide as long as a dialog like "Configure Panel" is open, even upon clicking somewhere else on the desktop. But the panel does auto-hide once the dialog is closed. IMO this is absolutely the right thing to do.

I agree that it is helpful for the Panel to remain unhidden when right-clicking and opening "Configure Panel"; but IMO not for opening any other dialog (or application).  Two use cases:
1.  Right-click to open, e.g. 'Configure Task Manager'; the dialog remains open when clicking outside the dialog and/or for Panel mouse-over.
2.  A worse scenario; right-click an application in the quick launch, then open it; the panel is also stuck unhidden until Panel mouse-over.  This is probably just a result of the aforementioned remaining quick launch right-click issue.

**Comment by palinek** [comment]
@jeremywh7 Thanks for testing and pointing out the "forgotten" quicklauch menu. Fixed in @9df4de7

> 1. Right-click to open, e.g. 'Configure Task Manager'; the dialog remains open when clicking outside the dialog and/or for Panel mouse-over.

I don't agree here. Configure dialogs of all plugins are triggering the "no auto-hide until configure window closed" behaviour.

**Comment by jeremywh7** [comment]
Quick launch right-click confirmed fixed.
>I don't agree here. Configure dialogs of all plugins are triggering the "no auto-hide until configure window closed" behaviour.
I agree now; I was more concerned about #[2] but that is now resolved w/ the general quick launch fix.  Thanks @palinek !

**Pull request merged**
