### PR TITLE
new spacer plugin/widget

### PR DESCRIPTION
**Pull request by palinek**
Width is configurable, style can be changed in theme.
Fixes lxde/lxqt#394.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Looks great! @palinek, @jleclanche, @intialonso the plugin is invisible (as it should be, I think) and that makes it hard to find it (if the user wants to right-click, for example). How should it be done? If that's ok that way, I'll ask @palinek to rebase the PR and I will merge it.

**Comment by paulolieuthier** [comment]
@palinek another thing, please add the plugin to the list in the main `CMakeLists.txt` to make it default. See the diff:
```dif
diff --git a/CMakeLists.txt b/CMakeLists.txt
index dcd4d65..9f98621 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -193,6 +193,12 @@ if(TASKBAR_PLUGIN)
   add_subdirectory(plugin-taskbar)
 endif()
 
+setByDefault(SPACER_PLUGIN Yes)
+if(SPACER_PLUGIN)
+    set(ENABLED_PLUGINS ${ENABLED_PLUGINS} "Spacer")
+    add_subdirectory(plugin-spacer)
+endif()
+
 setByDefault(TRAY_PLUGIN Yes)
 if(TRAY_PLUGIN)
     set(ENABLED_PLUGINS ${ENABLED_PLUGINS} "System Tray")
```

**Comment by intialonso** [comment]
Maybe it can have different look options (invisible, dots, line).

**Comment by palinek** [comment]
Is it reasonable to have it configurable for plugin? Look of the widget can be configured in theme, eg:
```qss
#Spacer {
    border: 3px solid #4C4C4C;
    background: #1A80B6;
}

**Comment by palinek** [comment]
@paulolieuthier Ad: CMakeLists.txt ... of course I made this, but it landed in different local branch :)

**Comment by intialonso** [comment]
@palinek I think that this can be used also as a separator and the user could want to have it visible (as a line or dots, or even just a dot) or invisible, that is why it could have different looks and the option must be presented to the user, and those looks can be themed in the qss, something like this:

```
#Spacer > lined {
    border: 3px solid #4C4C4C;
    background: #1A80B6;
}

#Spacer > doted {
    border: 3px doted #4C4C4C;
    background: #1A80B6;
}

#Spacer > invisible {
    border: 3px doted transparent;
    background: transparent;
}
```

rect4171

**Comment by palinek** [comment]
@intialonso it sounds reasonable... but I think owners should agree this

**Comment by paulolieuthier** [comment]
I agree with that approarch, but that's for another PR.

**Comment by paulolieuthier** [comment]
@palinek please rebase this PR. The invisibility thing will be solved in the themes.

**Comment by paulolieuthier** [comment]
If you need help, rebasing, see [this](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase/).

**Comment by palinek** [comment]
@paulolieuthier i've rebased this earlier today

**Comment by palinek** [comment]
@intialonso I'm not sure about this:
```qss
#Spacer > lined {
    border: 3px solid #4C4C4C;
    background: #1A80B6;
}
```
For such selector the Spacer widget sholud have a child widget which is object of class lined, right?
Wouldn't it be better to declare a property, e.g. type and style it following way?:
```qss
#Spacer[type="lined"] {
    border: 3px solid #4C4C4C;
    background: #1A80B6;
}
```
Proprety type will be configurable per widget instance => via editable combo box (3 predefined values lined, doted, invisible) => user can input other than predefined value and fiddle with theme qss to achieve what he/she wants.

**Comment by intialonso** [comment]
Yes, that looks fine, my approach was just a quick view.

**Comment by paulolieuthier** [comment]
@palinek exactly. Can you work on that?

**Comment by palinek** [comment]
@paulolieuthier yes, I'm trying ...

**Pull request merged**
