### PR TITLE
Workaround to the QStringLiteral static finalization bug

### PR DESCRIPTION
**Pull request by luis-pereira**
Replacing QStringLiteral by (QLatin1String/QString)
See bug report: https://bugreports.qt.io/browse/QTBUG-49061

### CODE REVIEW

**Comment by palinek** [comment]
@luis-pereira the bug isn't event accepted yet.... Did you see the #256? It solves the "QStringLiteral problem"...

**Comment by palinek** [comment]
Well... let's merge it

**Comment by luis-pereira** [comment]
@palinek This is as compromise solution, although temporary.

**Comment by luis-pereira** [comment]
Ok. Shiping it.

**Comment by palinek** [comment]
It seems that it will not be a temporary workaround... as the reported Qt bug was rejected/closed.

**Pull request merged**
