### PR TITLE
panel: Add "Lock Panel" functionality

### PR DESCRIPTION
**Pull request by palinek**
closes lxde/lxqt#1000

### CODE REVIEW

**Comment by stefonarch** [comment]
Works fine here, some screenshots:
schermata14
schermata13

**Comment by paulolieuthier** [comment]
Any reason why not to hide the actions instead of disabling?

**Comment by pmattern** [comment]
May be a matter of taste, but I think it's better when they're disabled / "grayed out" as this makes the correlation to the new feature "Lock this panel" and hence the functionality of the latter more obvious.

**Comment by luis-pereira** [comment]
I was not expecting that the it also disabled the Configure action.
@palinek Is this intended ?

**Comment by stefonarch** [comment]
Does  locking not mean  locking also position, size? For me it makes sense.

**Comment by palinek** [comment]
Yes, disabling config was intentional. Also I prefer disabling the actions instead of hiding them to let the user know what is not acessible if locked.

**Comment by luis-pereira** [comment]
@palinek I wasn't expecting it to also do a configuration disable. But I'm Ok with it.
GTM

**Pull request merged**
