### PR TITLE
implement drag/drop for PowerManager and ScreenSaver actions

### PR DESCRIPTION
**Pull request by dbluelle**
see https://github.com/lxde/lxde-qt/issues/319

### CODE REVIEW

**Comment by jleclanche** [comment]
@paulolieuthier so now we have the lxqt-leave stuff in, can this be closed or?

**Comment by paulolieuthier** [comment]
lxqt-leave doesn't fix this bug. The items in the "Leave" menu are not draggable and all. Maybe we should try to address it later, as lxqt-leave provides equivalent draggable items.

**Comment by dbluelle** [comment]
Well, AFAIK there is no official section for "leave session" in the menu specs, so the lxqt-leave items are put in the "other" section, as reported by agaida: https://github.com/lxde/lxqt/issues/437 .
So I had to add this PR to ensure the leave items that are added at the bottom of the menu are draggable.
The problem is that with this patch we now implicitly add the dependency of lxqt-session to lxqt-panel.
Any suggestions?

**Comment by jleclanche** [comment]
@paulolieuthier Well the lxqt-leave desktop items should be used over the custom stuff we currently use. That way they are draggable, that was the whole point of this endeavour.

@dbluelle Can you do this? See lxde/lxqt#437

**Comment by dbluelle** [comment]
@jleclanche What do you mean by "should be used over the custom stuff" ?
Should we somehow detect at runtime if lxqt-leave is available?

**Comment by paulolieuthier** [comment]
The current items are provided by lxqt-powermanagement.

**Comment by jleclanche** [comment]
We should use the lxqt-leave desktop files to populate the "Leave" submenu. That was the whole point of this exercise.

**Comment by dbluelle** [comment]
So then why not just merge this PR ?
It does exactly that.

**Comment by jleclanche** [comment]
I didn't see you updated it. I'll review.

**Pull request closed without merging**
