### PR TITLE
taskbar: Enhance moving buttons

### PR DESCRIPTION
**Pull request by palinek**
This sould resolve problems with moving taskbar buttons.

closes lxde/lxqt#681

### CODE REVIEW

**Comment by paulolieuthier** [comment]
As discussed on IRC with @palinek, the first commit breaks a feature I had previously implemented. Supposed one has three windows opended and he wants to move the first button to the middle. When moving the button, he drops it in the left half of the third button. Where should the button be dropped?

I believe it should be dropped in the middle. When I wrote the DND, I imagined a vertical line in the middle of each button. A dropped button must be placed in the middle of the closest vertical lines (left and right). In the situation above, the first button could be placed in the third position by moving it past the third button's half (after its imaginary vertical line).

@palinek disagrees, and it also makes sense. He believes (forgive me if I didn't get you right) the dropped button must be placed in the position of the button where the drop occured.

@pmattern, @luis-pereira, @jleclanche or anybody else interested: what are your toughts?

**Comment by palinek** [comment]
Well... there was definitely a discrepancy in the destination position. The @58a3faf implements paulo's "virtual center line" logic.

**Comment by paulolieuthier** [comment]
GTM now.

**Comment by luis-pereira** [comment]
GTM

**Comment by jleclanche** [comment]
@paulolieuthier I don't think an exact model matters, because we should have visual feedback (buttons moving as the mouse drags them, or at least a highlight separator where the drop will occur. Problem is we don't have either of those things right now...

**Comment by jleclanche** [comment]
gtm either way, but i'd favour the simplest logic.

**Comment by paulolieuthier** [comment]
> ... because we should have visual feedback...

Agreed.

**Comment by paulolieuthier** [comment]
@palinek shipt it :+1:.

**Pull request merged**
