### PR TITLE
Update clock_it_IT.ts

### PR DESCRIPTION
**Pull request by stefonarch**
added italian translation

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Reverted, for it triggers a compile error.

**Comment by stefonarch** [comment]
Cannot reproduce it here... compiles well

**Comment by paulolieuthier** [comment]
```
Parse error at /home/paulo/Workspace/lxqt/lxqt-panel/plugin-clock/translations/clock_it_IT.ts:1:39: XML declaration not at start of document.
```

**Comment by jleclanche** [comment]
I'm guessing it's because of the leading space. I saw it but didn't think anything of it; I shouldn't have. Sorry.

**Pull request merged**
