### PR TITLE
taskbar: Add "raise on wheel" configuration

### PR DESCRIPTION
**Pull request by palinek**
Required in https://github.com/lxde/lxqt/issues/104#issuecomment-257013010

### CODE REVIEW

**Comment by stefonarch** [comment]
Works fine, but would something like "cycle through windows on wheel scroll" not be more clear?

**Comment by palinek** [comment]
> Works fine, but would something like "cycle through windows on wheel scroll" not be more clear?

Right, pushed fixup.

**Comment by alexhenrie** [comment]
The variable name "mRaiseOnWheelScroll" and preference name "raiseOnWheelScroll" are a still little weird, but I definitely support having a preference for this.

**Comment by palinek** [comment]
> The variable name "mRaiseOnWheelScroll" and preference name "raiseOnWheelScroll" are a still little weird,

Force-pushed update...

**Comment by alexhenrie** [comment]
Looks good. The only other change I would make is turning this feature off by default, but nevertheless having a preference is a big improvement.

**Comment by palinek** [comment]
> The only other change I would make is turning this feature off by default

Sorry, but I believe, that not-changing default behaviour (or breaking user configuration) is the best for (continuos) user experience. Therefore the default value is _on_.

**Comment by pmattern** [comment]
> Sorry, but I believe, that not-changing default behaviour (or breaking user configuration) is the best for (continuos) user experience.

Definitely, yes.

**Comment by alexhenrie** [comment]
The "cycle on wheel" feature is a very annoying change from LDXE, but like I said, merging this pull request would be a big improvement.

**Comment by palinek** [comment]
>  merging this pull request would be a big improvement.

I'm waiting for an LXQt member for opinion. @pmattern Did you test this?

**Comment by tsujan** [comment]
I also think that the default behavior shouldn't be changed.

**Comment by pmattern** [comment]
@palinek 
Works as expected "bare metal". In virtual KVM/QEMU machines setting "Cycle windows on wheel scrolling" doesn't seem to have an effect and the "cycling" seems always to be disabled. But this is probably an issue of the virtual machine we do not have to look into any further.

**Pull request merged**
