### PR TITLE
plugin-clock: configurable first day of week

### PR DESCRIPTION
**Pull request by palinek**
fixes lxde/lxqt#193

### CODE REVIEW

**Comment by paulolieuthier** [comment]
I get a segfault when changing a setting with no previous settings for the plugin.
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000446e39 in LxQtClockConfiguration::saveSettings (this=0x94a780)
    at /home/paulo/Workspace/lxqt/lxqt-panel/plugin-clock/lxqtclockconfiguration.cpp:263
263         mSettings.setValue("firstDayOfWeek", dynamic_cast<QStandardItemModel&>(*ui->firstDayOfWeekCB->model()).item(ui->firstDayOfWeekCB->currentIndex(), 0)->data(Qt::UserRole));
(gdb) bt
#0  0x0000000000446e39 in LxQtClockConfiguration::saveSettings (this=0x94a780)
    at /home/paulo/Workspace/lxqt/lxqt-panel/plugin-clock/lxqtclockconfiguration.cpp:263
#1  0x0000000000448cd7 in LxQtClockConfiguration::qt_static_metacall (_o=0x94a780, 
    _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffd570)
    at /home/paulo/Workspace/lxqt/lxqt-panel/build/plugin-clock/moc_lxqtclockconfiguration.cpp:78
#2  0x00007ffff43b9309 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#3  0x00007ffff5017a62 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff4d6aba5 in ?? () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff4d6b7c9 in ?? () from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff4d6b984 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff4cb2e08 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff4c6facc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff4c757d1 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff4388d1b in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007ffff4c742ea in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff4ccb530 in ?? () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff4ccd6a3 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff4c6facc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#15 0x00007ffff4c74f10 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff4388d1b in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#17 0x00007ffff46b7752 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#18 0x00007ffff46b9305 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#19 0x00007ffff469e1ef in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#20 0x00007fffeb9b11d0 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#21 0x00007ffff74b771d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#22 0x00007ffff74b7a08 in ?? () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff74b7abc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff43e1077 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff43867b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#26 0x00007ffff438e18c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#27 0x0000000000423fda in main (argc=1, argv=0x7fffffffe3a8)
    at /home/paulo/Workspace/lxqt/lxqt-panel/panel/main.cpp:109
```

**Comment by palinek** [comment]
@paulolieuthier fixed that (forgot the default value when there was no value set in settings yet)

**Comment by paulolieuthier** [comment]
GTM.

**Comment by palinek** [comment]
Landed in 61081b875a802cb6df36765b4acd04d8d7cec27a

**Pull request closed without merging**
