### PR TITLE
configurable bar width in plugin-cpuload

### PR DESCRIPTION
**Pull request by palinek**
Just thought that could be nice to have configuration of width in plugin-cpuload (as it is in plugin-sensors).

### CODE REVIEW

**Comment by palinek** [comment]
Nobody intrested?

**Comment by paulolieuthier** [comment]
@palinek I am interested. Your contribution is appreciated, I'll take a look at it soon.

**Comment by paulolieuthier** [comment]
@palinek it would be nice to rephrase the commit messages to make it clear their changes belong to the cpuload plugin only. Besides that, the three commits could also be squashed into a single one. Name suggestion: `plugin-cpuload: configurable bar width`.

**Comment by jleclanche** [comment]
Leave a separate commit for the coding style fix like you did please.

**Comment by palinek** [comment]
@paulolieuthier commits merged, message changed...

**Comment by paulolieuthier** [comment]
Landed in lxde/lxqt-panel@4f8c4061bb531dee29c32bd74c4952e7006cb902. @palinek thanks for your contribution :smile:.

**Pull request closed without merging**
